[package]
name = "prover"
version = "0.1.0"
edition = "2024"

[dependencies]
pico-sdk = { workspace = true }
bincode = "1.3.3"
sha256-lib = { path = "../lib" }
serde = { workspace = true }
utils = { path = "../../../utils" }
sha2 = { version = "0.10.8", default-features = false }