[workspace]
members = [
  "fibonacci/lib",
  "fibonacci/program",
  "fibonacci/script",
  "sha2/lib",
  "sha2/program",
  "sha2/script",
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "0.7.7"